# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(287, 300)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 180, 131, 71))
        self.pushButton.setStyleSheet("background-color: rgb(179, 204, 43);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Consolas\";\n"
"border-radius: 20px;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, -50, 511, 141))
        self.label.setMinimumSize(QtCore.QSize(511, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/download1_180x120.jpg"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 90, 131, 81))
        self.label_3.setStyleSheet("font: 75pt \"Consolas\";\n"
"color: rgb(156, 188, 4);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Старт"))
import ii_rc